/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    IButtonSrc: typeof import('./../../src/components/IButton/src/index.vue')['default']
    IChartSrc: typeof import('./../../src/components/IChart/src/index.vue')['default']
    ICodeEditorSrc: typeof import('./../../src/components/ICodeEditor/src/index.vue')['default']
    IDataDisplaySrcDataBox: typeof import('./../../src/components/IDataDisplay/src/DataBox.vue')['default']
    IDescriptionSrc: typeof import('./../../src/components/IDescription/src/index.vue')['default']
    IDrawerSrc: typeof import('./../../src/components/IDrawer/src/index.vue')['default']
    IFormSrc: typeof import('./../../src/components/IForm/src/index.vue')['default']
    IFormSrcComponentsFormItem: typeof import('./../../src/components/IForm/src/components/FormItem.vue')['default']
    IFormSrcComponentsSelect: typeof import('./../../src/components/IForm/src/components/Select.vue')['default']
    IFormSrcComponentsUpload: typeof import('./../../src/components/IForm/src/components/Upload.vue')['default']
    IIconSrcIcon: typeof import('./../../src/components/IIcon/src/Icon.vue')['default']
    IIconSrcSvgIcon: typeof import('./../../src/components/IIcon/src/SvgIcon.vue')['default']
    ITableSrc: typeof import('./../../src/components/ITable/src/index.vue')['default']
    ITableSrcComponentsTableSearch: typeof import('./../../src/components/ITable/src/components/TableSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestSrc: typeof import('./../../src/components/Test/src/index.vue')['default']
  }
}
