/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FormItem: typeof import('./../../src/components/Form/src/components/FormItem.vue')['default']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    Icon: typeof import('./../../src/components/Icon/src/Icon.vue')['default']
    IconCommunity: typeof import('./../../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../../src/components/icons/IconTooling.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../../src/components/Form/src/components/Select.vue')['default']
    Src: typeof import('./../../src/components/Button/src/index.vue')['default']
    SvgIcon: typeof import('./../../src/components/Icon/src/SvgIcon.vue')['default']
    TableSearch: typeof import('./../../src/components/Table/src/components/TableSearch.vue')['default']
    TheWelcome: typeof import('./../../src/components/TheWelcome.vue')['default']
    Upload: typeof import('./../../src/components/Form/src/components/Upload.vue')['default']
    WelcomeItem: typeof import('./../../src/components/WelcomeItem.vue')['default']
  }
}
